### ISSUE TITLE
Idea: Common Job Interview Questions

### ISSUE THREAD

**Issue by SZ-Berlin** [thakurdiwakar/Interview-Skills-Development#19]
How do you debug a reported issue? 

In what order do you proceed? 

What is particularly easy / difficult for you when debugging?

The aim of these questions is to find out if you know a common procedure and if you are aware of your own difficulties and know when to ask a team member.

**Comment by thakurdiwakar** [comment]
Can i assign it to you?

**Comment by SZ-Berlin** [comment]
I'm sorry, no. 
Someone is welcome to include it, but unfortunately I don't have the capacity. 
Thank you for your work.

**Comment by thakurdiwakar** [comment]
Okay, thank you for creating the issue.

**Comment by Vaishwanavi** [comment]
I can add questions related to recursion,sorting ,searchings.please assign thise issue to me.

**Comment by thakurdiwakar** [comment]
@Vaishwanavi assigned

**Comment by Vaishwanavi** [comment]
@thakurdiwakar  #34 please merge the pr
