### ISSUE TITLE
Error:Code of Conduct link is dead link

### ISSUE THREAD

**Issue by Learningcomputers777** [thakurdiwakar/Interview-Skills-Development#38]
In the CONTRIBUTING.md file(https://github.com/thakurdiwakar/Interview-Skills-Development/blob/main/CONTRIBUTING.md) 
There is code of conduct mentioned in the file but when we clock on it to does open a dead link and says we do not have any code of conduct.md file.
![Screenshot 2023-10-23 at 22 05 59](https://github.com/thakurdiwakar/Interview-Skills-Development/assets/73050770/ecf677fa-b295-4c80-bfdc-5d95dab05e3c)

**Comment by Learningcomputers777** [comment]
I would like to solve this issue by adding a CODE OF CONDUCT link from a website called Contributor Covenant(https://www.contributor-covenant.org) which is used by many open source technologies and companies since 2014.

**Comment by Learningcomputers777** [comment]
Assign this to me

**Comment by Learningcomputers777** [comment]
That is one way to do it.
If you want me to create a CODE_OF_CONDUCT.md file with the information from the contributor covenant site and I would refer that link in the CONTRINUTING.md file. This is another way.

**Comment by Learningcomputers777** [comment]
That is one way to do it.
If you want me to create a CODE_OF_CONDUCT.md file with the information from the contributor covenant site and I would refer that link in the CONTRINUTING.md file. This is another way.

Can you make it hackoctober fest label?
Assign it to me.

**Comment by Learningcomputers777** [comment]
That is one way to do it.
If you want me to create a CODE_OF_CONDUCT.md file with the information from the contributor covenant site and I would refer that link in the CONTRIBUTING.md file. This is another way.

Can you make it hackoctober fest label?
Assign it to me.

**Comment by Learningcomputers777** [comment]
In which way would you want me to do it.

**Comment by thakurdiwakar** [comment]
> I would like to solve this issue by adding a CODE OF CONDUCT link from a website called Contributor Covenant(https://www.contributor-covenant.org) which is used by many open source technologies and companies since 2014.

you can use this

**Comment by Learningcomputers777** [comment]
I will close the issue then.

**Comment by Learningcomputers777** [comment]
I will close the issue.

**Comment by thakurdiwakar** [comment]
yes
