### ISSUE TITLE
I think Machine learning basic questions should also be added

### ISSUE THREAD

**Issue by ankit1576** [thakurdiwakar/Interview-Skills-Development#64]
Machine learning is very fasltly growing and some concept are not very clear to every one i can help you by providing all the basic imp question for ML

**Comment by ankit1576** [comment]
assign it to me i'll definetly try my best

**Comment by thakurdiwakar** [comment]
You are welcome to begin your work, @ankit1576

**Comment by ankit1576** [comment]
@thakurdiwakar btw Done accept PR and i can close this issue
