### ISSUE TITLE
Want to add project ideas folder with all basics to advance project ideas

### ISSUE THREAD

**Issue by ankit1576** [thakurdiwakar/Interview-Skills-Development#69]
Good projects are also be part of the Interview
I think we need to add a project ideas folder which consist of all the ideas related to the projects

**Comment by thakurdiwakar** [comment]
You may begin your task now. @ankit1576

**Comment by ankit1576** [comment]
thankyou @thakurdiwakar for your continuos support

**Comment by ankit1576** [comment]
i have updated one new folder name project ideas and also updated readme

**Comment by ankit1576** [comment]
@thakurdiwakar  done
