### ISSUE TITLE
Typos and Presentation of content of repos

### ISSUE THREAD

**Issue by ankit1576** [thakurdiwakar/Interview-Skills-Development#73]
I can see many typos and Small case and upper case word all mixed up ,want to change the Readme.md file by adding some glyph icons
and want to correct some typos and case errors 
This will definitely help to increase the reach of the repository as beautiful presentation attract more user to read the content i can do this pls assign this to me

**Comment by thakurdiwakar** [comment]
@ankit1576

**Comment by ankit1576** [comment]
@thakurdiwakar Done merge PR
