### ISSUE TITLE
We can add Some Interviews Question Related to CSS 

### ISSUE THREAD

**Issue by Ankita-0302** [thakurdiwakar/Interview-Skills-Development#75]
Please assign me the task I Know few Question

**Comment by thakurdiwakar** [comment]
okay add your question in web.md and also update the readme.md @Ankita-0302

**Comment by Ankita-0302** [comment]
send you the pull request please accept

**Comment by Ankita-0302** [comment]
hey is their any issue you are facing while merging the code?
