### ISSUE TITLE
I have few Java Programming Questions  to add

### ISSUE THREAD

**Issue by Ankita-0302** [thakurdiwakar/Interview-Skills-Development#87]
## Describe the question/project you want to add with tech stack
 I Have few java Programing questions  which I want to add

## Expected behavior
 6 programs on java language(palindrome, reverse no. etc .

**Comment by thakurdiwakar** [comment]
Describe the question/project you want to add with tech stack
Expected behavior
Screenshots (optional)
Additional context (optional)


read it again then create issue @Ankita-0302

**Comment by Ankita-0302** [comment]
@thakurdiwakar please check and assign the task
